### ISSUE TITLE
Forced port 8081 even when not wanted for Webhooks

### ISSUE THREAD

**Issue by jaysonng** [netreconlab/parse-server-swift#44]
Today I'm trying to get my Parse-Server-Swift setup on Heroku. 

Regarding webhooks where on restart of the server, we delete and recreate the webhooks. 

However, right now, the Port is always added. By default, if there's no port in the Environments, port 8081 is setup by default and added to the webhook URL.

Is there a way we can have 8081 not show up? As of now, after restart, my webooks revert back to 

`
http://sampledomain.com:8081/xxx/get 
`

when I just need 

`
http://sampledomain.com/xxx/get
`

thanks,

**Comment by jaysonng** [comment]
I was thinking of adding a check for localhost || 127.0.0.1 before adding port ?

**Comment by cbaker6** [comment]
See #57 and read through links. If you want to set the hostname along with binding to ports 80 or 443, you should be setting the applicable environment variables in your image to allow this properly.

**Comment by cbaker6** [comment]
It’s it’s looks like you are somehow exposing your parser-server-swift directly to the internet which is typically not recommended. Most people would place their server behind some type of reverse proxy link nginx or haproxy. Did you read through the links in https://github.com/netreconlab/parse-server-swift/issues/44#issuecomment-1890603488, particular the second link in the PR in Vapor?

if you really want to do what you are mentioning, you should set your port to a default port of “80” or “443”, which should allow you to do `http://sampledomain.com/xxx/get` and `https://sampledomain.com/xxx/get` respectively

**Comment by cbaker6** [comment]
You can run docker images directly on Heroku, you can search for tutorials or modify the one-button deployment of parse-hipaa, https://github.com/netreconlab/parse-hipaa/tree/parse-swift#heroku. You can do the same for parse-server-swift

**Comment by jaysonng** [comment]
thanks :)

**Comment by jaysonng** [comment]
> You can run docker images directly on Heroku, you can search for tutorials or modify the one-button deployment of parse-hipaa, https://github.com/netreconlab/parse-hipaa/tree/parse-swift#heroku. You can do the same for parse-server-swift

will a docker install with parse-server and parse-server-swift run normally on a windows install for local development?

**Comment by cbaker6** [comment]
It should, docker containers should work the same way on all types of machines, you just need to bind the exposed port
